package com.ramatonn.todo.util

const val CLOCK_NOTIFICATION_CHANNEL_ID = "CLOCK_NOTIFICATION_CHANNEL_ID"
const val CLOCK_NOTIFICATION_CHANNEL = "CLOCK_NOTIFICATION_CHANNEL"

const val TASK_NOTIFICATION_CHANNEL_ID = "TASK_NOTIFICATION_CHANNEL_ID"
const val TASK_NOTIFICATION_CHANNEL = "TASK_NOTIFICATION_CHANNEL"
