package com.ramatonn.todo.util

const val STOPWATCH_NOTIFICATION_CHANNEL_ID = "STOPWATCH_NOTIFICATION_CHANNEL_ID"
const val STOPWATCH_NOTIFICATION_CHANNEL = "STOPWATCH_NOTIFICATION_CHANNEL"
const val STOPWATCH_NOTIFICATION_ID = 1

const val TIMER_NOTIFICATION_CHANNEL_ID = "TIMER_NOTIFICATION_CHANNEL_ID"
const val TIMER_NOTIFICATION_CHANNEL = "TIMER_NOTIFICATION_CHANNEL"
const val TIMER_NOTIFICATION_ID = 2

const val CLOCK_STATE = "CLOCK_STATE"
const val CLOCK_TYPE = "CLOCK_TYPE"
const val ACTIVE_DURATION = "ACTIVE_DURATION"
const val REST_DURATION = "REST_DURATION"
const val ROUNDS = "ROUNDS"

const val ALERT_NAME = "ALERT_NAME"
const val ALERT_SOUND = "ALERT_SOUND"
const val ALERT_MESSAGE = "ALERT_MESSAGE"
const val ALERT_END_TIME = "ALERT_END_TIME"
const val ALERT_START_TIME = "ALERT_START_TIME"
const val ALERT_CHANNEL = "ALERT_CHANNEL"
const val ALERT_CHANNEL_ID = "ALERT_CHANNEL_ID"

const val TASK_TITLE = "TASK_TITLE"
const val TASK_MESSAGE = "TASK_MESSAGE"
const val TASK_DATE = "TASK_DATE"
const val TASK_TIME = "TASK_TIME"
const val TASK_CHANNEL = "TASK_CHANNEL"
const val TASK_CHANNEL_ID = "TASK_CHANNEL_ID"

const val ACTION_SERVICE_PAUSE = "ACTION_SERVICE_PAUSE"
const val ACTION_SERVICE_RESUME = "ACTION_SERVICE_RESUME"
const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"

const val CLICK_REQUEST_CODE = 100
const val CANCEL_REQUEST_CODE = 101
const val PAUSE_REQUEST_CODE = 102
const val RESUME_REQUEST_CODE = 103

const val TASK_NOTIFICATION_CHANNEL_ID = "TASK_NOTIFICATION_CHANNEL_ID"
const val TASK_NOTIFICATION_CHANNEL = "TASK_NOTIFICATION_CHANNEL"
const val TASK_NOTIFICATION_ID = 3

